name: Sip Social
favicon: null
layout_spectrum: 0.95125
typography_spectrum: 0.77234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0106'
    - '#6e5bcc'
    - '#c5461c'
    - '#fe7d3e'
    - '#781b1d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
