name: Sip Social
favicon: null
layout_spectrum: 0.24056
typography_spectrum: 0.77234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0005'
    - '#873249'
    - '#fcf9f4'
    - '#c26441'
    - '#ffb56c'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
