name: Sip Social
favicon: null
layout_spectrum: 0.23139454191550612
typography_spectrum: 0.77234
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3184734503738582
  lightness: 0.20254503469914198
  saturation: 0.7018450149334967
  rhythmicContrast: 0.28972242143936455
purpose: []
